import {
  MandiPrice,
  WeatherDay,
  ProduceLot,
  LotOffer,
  ColdStorageFacility,
  TransportOption,
  VerifiedBuyerMatch,
  TransactionOrder,
  GrievanceRecord,
  PriceForecastPoint,
  GovtCalamityClaimRecord,
  CattleKeeper,
  RegisteredAccount,
  FarmerVehicle,
  TransportBookingRequest,
  SplitTransportPool,
} from "./types";
import { getDynamicMandiPrices } from "./utils/mandiLiveService";

export const initialMandiPrices: MandiPrice[] = getDynamicMandiPrices();

const formatShortEnDate = (d: Date): string => {
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  return `${months[d.getMonth()]} ${d.getDate()}`;
};

export const getDynamicWeatherData = (baseDate: Date = new Date()): WeatherDay[] => {
  const templates = [
    {
      day: "Today",
      tempMax: 31,
      tempMin: 22,
      condition: "Partly Cloudy" as const,
      rainProb: 20,
      humidity: 65,
      harvestRisk: "Low" as const,
      advice: "Optimal field conditions for plucking vegetables and sun-drying pulses.",
    },
    {
      day: "Tomorrow",
      tempMax: 29,
      tempMin: 21,
      condition: "Moderate Rain" as const,
      rainProb: 65,
      humidity: 78,
      harvestRisk: "Medium" as const,
      advice: "Early morning harvest advised. Keep tarpaulin ready for standing crates.",
    },
    {
      day: "Day 3",
      tempMax: 26,
      tempMin: 20,
      condition: "Heavy Rain" as const,
      rainProb: 92,
      humidity: 88,
      harvestRisk: "High" as const,
      advice: "⚠️ Heavy Rain in 2 Days! Harvest ripe tomatoes & soft greens now or move to cold storage.",
    },
    {
      day: "Day 4",
      tempMax: 27,
      tempMin: 20,
      condition: "Thunderstorm" as const,
      rainProb: 85,
      humidity: 85,
      harvestRisk: "High" as const,
      advice: "Avoid road transport without waterproof vehicle covers. Keep drainage trenches open.",
    },
    {
      day: "Day 5",
      tempMax: 29,
      tempMin: 21,
      condition: "Partly Cloudy" as const,
      rainProb: 35,
      humidity: 72,
      harvestRisk: "Low" as const,
      advice: "Weather clears up. Expect high mandi demand as post-rain supply is restricted.",
    },
    {
      day: "Day 6",
      tempMax: 30,
      tempMin: 22,
      condition: "Sunny" as const,
      rainProb: 15,
      humidity: 60,
      harvestRisk: "Low" as const,
      advice: "Peak selling window! Prices anticipated to surge due to low mandi arrivals.",
    },
    {
      day: "Day 7",
      tempMax: 31,
      tempMin: 22,
      condition: "Sunny" as const,
      rainProb: 10,
      humidity: 58,
      harvestRisk: "Low" as const,
      advice: "Favorable dry days ahead. Good for grading and lot packing.",
    },
  ];

  return templates.map((t, idx) => {
    const d = new Date(baseDate.getFullYear(), baseDate.getMonth(), baseDate.getDate() + idx);
    const yyyy = d.getFullYear();
    const mm = String(d.getMonth() + 1).padStart(2, "0");
    const dd = String(d.getDate()).padStart(2, "0");
    return {
      ...t,
      date: formatShortEnDate(d),
      dateIso: `${yyyy}-${mm}-${dd}`,
    };
  });
};

export const initialWeatherData: WeatherDay[] = getDynamicWeatherData();

export const initialLots: ProduceLot[] = [
  {
    id: "lot-1025",
    farmerId: "f-01",
    farmerName: "Ramesh Patil",
    farmerPhone: "+91 98220 14890",
    farmerLocation: "Dindori, Nashik (12 km from city)",
    crop: "Tomato (Hybrid - Vaishnavi)",
    variety: "Firm Salad Grade",
    quantityKg: 2000,
    availableKg: 2000,
    qualityGrade: "Grade A",
    harvestDate: "Today (Fresh Plucked)",
    askingPricePerKg: 32,
    status: "Bidding",
    offersCount: 3,
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80",
    organicCertified: true,
    minOrderQuantityKg: 50,
    distanceKm: 12,
  },
  {
    id: "lot-1030",
    farmerId: "f-05",
    farmerName: "Kailas Jagtap",
    farmerPhone: "+91 98231 66543",
    farmerLocation: "Khed, Pune (14 km from market)",
    crop: "Tomato (Fresh Grade A - Polyhouse)",
    variety: "Firm Plump Salad Grade (<5% defect)",
    quantityKg: 1500,
    availableKg: 1500,
    qualityGrade: "Grade A",
    harvestDate: "Today (Morning Plucked)",
    askingPricePerKg: 28,
    status: "Active",
    offersCount: 2,
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80",
    organicCertified: true,
    minOrderQuantityKg: 25,
    distanceKm: 14,
    trustMetrics: {
      confidenceScore: 98,
      gradeAccuracyScore: 99,
      onTimeDispatchScore: 97,
      weightAccuracyScore: 100,
      completedDeliveriesCount: 52,
      buyerSatisfactionRating: 4.9,
      totalBuyerReviews: 44,
      landRecordVerified: true,
      kisanCreditVerified: true,
      labAssayCertified: true,
      moisturePercent: 8.5,
      brixSweetnessScore: 5.4,
      recentBuyerReviews: [
        {
          buyerName: "Metro Fresh Retail - Pune",
          buyerType: "Retail Chain",
          rating: 5,
          qualityComment: "Exceptional uniform red color and firm skin. Zero transit decay.",
          date: "3 days ago",
        },
        {
          buyerName: "Swad Agro Processors",
          buyerType: "Processing Unit",
          rating: 4.9,
          qualityComment: "Accurate 20kg crates weighing, pristine quality matching sample.",
          date: "1 week ago",
        },
      ],
    },
  },
  {
    id: "lot-1026",
    farmerId: "f-01",
    farmerName: "Ramesh Patil",
    farmerPhone: "+91 98220 14890",
    farmerLocation: "Dindori, Nashik (12 km from city)",
    crop: "Onion (Nashik Red)",
    variety: "Medium-Large Bulbs (<11% Moisture)",
    quantityKg: 5000,
    availableKg: 4200,
    qualityGrade: "Grade A",
    harvestDate: "3 days ago (Cured & Graded)",
    askingPricePerKg: 26,
    status: "Active",
    offersCount: 2,
    image: "https://images.unsplash.com/photo-1508747703725-719777637510?w=600&auto=format&fit=crop&q=80",
    organicCertified: false,
    minOrderQuantityKg: 25,
    distanceKm: 12,
    trustMetrics: {
      confidenceScore: 96,
      gradeAccuracyScore: 97,
      onTimeDispatchScore: 98,
      weightAccuracyScore: 99,
      completedDeliveriesCount: 68,
      buyerSatisfactionRating: 4.8,
      totalBuyerReviews: 53,
      landRecordVerified: true,
      kisanCreditVerified: true,
      labAssayCertified: true,
      moisturePercent: 10.2,
      recentBuyerReviews: [
        {
          buyerName: "BigBasket Hub - Nashik",
          buyerType: "Supermarket",
          rating: 4.9,
          qualityComment: "Well-cured red onions with tight skin, dry neck, and excellent storability.",
          date: "5 days ago",
        },
      ],
    },
  },
  {
    id: "lot-1027",
    farmerId: "f-02",
    farmerName: "Sunita Deshmukh",
    farmerPhone: "+91 94231 87612",
    farmerLocation: "Baramati, Pune (18 km from highway)",
    crop: "Potato (Jyoti Fresh)",
    variety: "Table & Chip Variety",
    quantityKg: 3500,
    availableKg: 3500,
    qualityGrade: "Grade B",
    harvestDate: "Yesterday",
    askingPricePerKg: 20,
    status: "Active",
    offersCount: 1,
    image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&auto=format&fit=crop&q=80",
    organicCertified: false,
    minOrderQuantityKg: 10,
    distanceKm: 18,
    trustMetrics: {
      confidenceScore: 93,
      gradeAccuracyScore: 94,
      onTimeDispatchScore: 95,
      weightAccuracyScore: 98,
      completedDeliveriesCount: 31,
      buyerSatisfactionRating: 4.7,
      totalBuyerReviews: 26,
      landRecordVerified: true,
      kisanCreditVerified: true,
      labAssayCertified: false,
      recentBuyerReviews: [
        {
          buyerName: "Kisan Wholesale Co",
          buyerType: "Wholesaler",
          rating: 4.7,
          qualityComment: "Good uniform medium tubers, minor soil presence as declared.",
          date: "12 days ago",
        },
      ],
    },
  },
  {
    id: "lot-1028",
    farmerId: "f-03",
    farmerName: "Tukaram Shinde",
    farmerPhone: "+91 98902 44321",
    farmerLocation: "Niphad, Nashik",
    crop: "Grapes (Thompson Seedless)",
    variety: "Export Quality Sweet 18° Brix",
    quantityKg: 1200,
    availableKg: 1200,
    qualityGrade: "Grade A",
    harvestDate: "Morning Harvest",
    askingPricePerKg: 82,
    status: "Active",
    offersCount: 4,
    image: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=600&auto=format&fit=crop&q=80",
    organicCertified: true,
    minOrderQuantityKg: 20,
    distanceKm: 28,
    trustMetrics: {
      confidenceScore: 99,
      gradeAccuracyScore: 100,
      onTimeDispatchScore: 99,
      weightAccuracyScore: 100,
      completedDeliveriesCount: 84,
      buyerSatisfactionRating: 5.0,
      totalBuyerReviews: 72,
      landRecordVerified: true,
      kisanCreditVerified: true,
      labAssayCertified: true,
      brixSweetnessScore: 18.4,
      recentBuyerReviews: [
        {
          buyerName: "Nature Fresh Exotics",
          buyerType: "Retail Chain",
          rating: 5,
          qualityComment: "Perfect 18° Brix sweetness, crisp berries, zero shatter.",
          date: "Yesterday",
        },
      ],
    },
  },
  {
    id: "lot-1029",
    farmerId: "f-04",
    farmerName: "Balasaheb Kadam",
    farmerPhone: "+91 97654 32109",
    farmerLocation: "Kopargaon, Ahmednagar",
    crop: "Wheat (Sharbati Golden)",
    variety: "Machine Cleaned Grain",
    quantityKg: 6000,
    availableKg: 6000,
    qualityGrade: "Grade A",
    harvestDate: "Stored 10 days in dry silo",
    askingPricePerKg: 34,
    status: "Active",
    offersCount: 2,
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&auto=format&fit=crop&q=80",
    organicCertified: true,
    minOrderQuantityKg: 50,
    distanceKm: 45,
    trustMetrics: {
      confidenceScore: 97,
      gradeAccuracyScore: 98,
      onTimeDispatchScore: 99,
      weightAccuracyScore: 100,
      completedDeliveriesCount: 42,
      buyerSatisfactionRating: 4.9,
      totalBuyerReviews: 38,
      landRecordVerified: true,
      kisanCreditVerified: true,
      labAssayCertified: true,
      moisturePercent: 9.1,
      recentBuyerReviews: [
        {
          buyerName: "Golden Flour Mills",
          buyerType: "Processing Unit",
          rating: 4.9,
          qualityComment: "Clean bold golden grains, strictly zero stones or weed seeds.",
          date: "4 days ago",
        },
      ],
    },
  },
];

export const initialOffers: LotOffer[] = [
  {
    id: "off-101",
    lotId: "lot-1025",
    buyerId: "b-01",
    buyerName: "Metro Fresh Retail - Pune",
    buyerType: "Retail Chain",
    offeredPricePerKg: 34,
    quantityRequestedKg: 1500,
    totalValue: 51000,
    distanceKm: 165,
    status: "Pending",
    timestamp: "12 mins ago",
    notes: "Requires Grade A packed in standard 20kg plastic crates. Immediate pickup.",
    buyerTrustMetrics: {
      confidenceScore: 99,
      avgPaymentDays: 0.5,
      paymentSpeedLabel: "Instant (Within 12 hours of delivery)",
      farmerReviewRating: 4.9,
      totalFarmerReviews: 48,
      completedTradesCount: 142,
      totalPayoutAmount: 4820000,
      disputeRatePercent: 0.2,
      kycVerified: true,
      gstApmcLicenseVerified: true,
      zeroDefaultGuarantee: true,
      recentReviews: [
        {
          farmerName: "Devidas Wagh",
          village: "Khed, Pune",
          rating: 5,
          daysToPay: 0.5,
          comment: "Full payment auto-released the exact afternoon truck was unloaded. Very clean dealing.",
          date: "Yesterday",
        },
        {
          farmerName: "Gopal Patil",
          village: "Niphad",
          rating: 4.9,
          daysToPay: 1,
          comment: "Exact weighbridge slip provided, zero unneeded deductions on tomato crates.",
          date: "4 days ago",
        },
      ],
    },
  },
  {
    id: "off-102",
    lotId: "lot-1025",
    buyerId: "b-02",
    buyerName: "Vashi Wholesalers Syndicate",
    buyerType: "Wholesaler",
    offeredPricePerKg: 32,
    quantityRequestedKg: 2000,
    totalValue: 64000,
    distanceKm: 175,
    status: "Pending",
    timestamp: "34 mins ago",
    notes: "Full lot buyout. Payment escrow funded. Ready to dispatch mini-truck.",
    buyerTrustMetrics: {
      confidenceScore: 96,
      avgPaymentDays: 1.0,
      paymentSpeedLabel: "Fast (Within 24 hours of delivery)",
      farmerReviewRating: 4.8,
      totalFarmerReviews: 62,
      completedTradesCount: 215,
      totalPayoutAmount: 8900000,
      disputeRatePercent: 0.4,
      kycVerified: true,
      gstApmcLicenseVerified: true,
      zeroDefaultGuarantee: true,
      recentReviews: [
        {
          farmerName: "Shankar Thorat",
          village: "Dindori",
          rating: 4.8,
          daysToPay: 1,
          comment: "High volume bulk buyer, always deposits 100% in escrow before lifting produce.",
          date: "3 days ago",
        },
      ],
    },
  },
  {
    id: "off-103",
    lotId: "lot-1025",
    buyerId: "b-03",
    buyerName: "Swad Agro Processors",
    buyerType: "Restaurant",
    offeredPricePerKg: 30,
    quantityRequestedKg: 800,
    totalValue: 24000,
    distanceKm: 45,
    status: "Pending",
    timestamp: "1 hour ago",
    notes: "Local delivery preferred. Can negotiate on crate return.",
    buyerTrustMetrics: {
      confidenceScore: 94,
      avgPaymentDays: 1.2,
      paymentSpeedLabel: "Reliable (1-2 Days Escrow)",
      farmerReviewRating: 4.7,
      totalFarmerReviews: 29,
      completedTradesCount: 88,
      totalPayoutAmount: 1850000,
      disputeRatePercent: 0.5,
      kycVerified: true,
      gstApmcLicenseVerified: true,
      zeroDefaultGuarantee: true,
      recentReviews: [
        {
          farmerName: "Prakash Shinde",
          village: "Sinnar",
          rating: 4.7,
          daysToPay: 1,
          comment: "Friendly local team, crates returned without breakage on next trip.",
          date: "6 days ago",
        },
      ],
    },
  },
  {
    id: "off-104",
    lotId: "lot-1026",
    buyerId: "b-04",
    buyerName: "BigBasket Hub - Nashik",
    buyerType: "Supermarket",
    offeredPricePerKg: 27,
    quantityRequestedKg: 2500,
    totalValue: 67500,
    distanceKm: 18,
    status: "Pending",
    timestamp: "45 mins ago",
    notes: "Will pickup via company fleet. 100% digital escrow payment.",
    buyerTrustMetrics: {
      confidenceScore: 98,
      avgPaymentDays: 0.8,
      paymentSpeedLabel: "Prompt (Same-Day / Next-Morning)",
      farmerReviewRating: 4.9,
      totalFarmerReviews: 76,
      completedTradesCount: 310,
      totalPayoutAmount: 12400000,
      disputeRatePercent: 0.1,
      kycVerified: true,
      gstApmcLicenseVerified: true,
      zeroDefaultGuarantee: true,
      recentReviews: [
        {
          farmerName: "Ankush Kute",
          village: "Pimpalgaon",
          rating: 5,
          daysToPay: 1,
          comment: "Direct gate entry with digital barcode scanner. Payment directly in Bank DBT.",
          date: "2 days ago",
        },
      ],
    },
  },
];

export const initialColdStorages: ColdStorageFacility[] = [
  {
    id: "cs-01",
    name: "Sahyadri Agro Cold Hub",
    location: "Dindori Road, Nashik",
    distanceKm: 3.2,
    totalCapacityMT: 600,
    availableCapacityMT: 180,
    temperatureRange: "2°C to 12°C (Humidity Controlled)",
    pricePerKgPerDay: 0.15, // ₹0.15 per kg/day or ₹4.5/month
    pricePerBagPerMonth: 110,
    rating: 4.8,
    verified: true,
    phone: "+91 94222 55431",
    suitableCrops: ["Tomato", "Grapes", "Pomegranate", "Capsicum"],
  },
  {
    id: "cs-02",
    name: "Kisan Cooperative Warehousing",
    location: "Niphad Bypass, Nashik",
    distanceKm: 8.5,
    totalCapacityMT: 1200,
    availableCapacityMT: 450,
    temperatureRange: "Ambient Ventilated + Cold Chamber",
    pricePerKgPerDay: 0.12,
    pricePerBagPerMonth: 95,
    rating: 4.6,
    verified: true,
    phone: "+91 98221 66723",
    suitableCrops: ["Onion", "Potato", "Garlic", "Ginger"],
  },
  {
    id: "cs-03",
    name: "FreshChill Multi-Chamber Logistics",
    location: "MIDC Ambad, Nashik",
    distanceKm: 14.0,
    totalCapacityMT: 850,
    availableCapacityMT: 95,
    temperatureRange: "-2°C to 15°C (Nitrogen Flush)",
    pricePerKgPerDay: 0.22,
    pricePerBagPerMonth: 140,
    rating: 4.9,
    verified: true,
    phone: "+91 99230 88910",
    suitableCrops: ["Grapes", "Strawberries", "Tomatoes", "Exotic Veggies"],
  },
];

export const initialTransportOptions: TransportOption[] = [
  {
    id: "tr-01",
    vehicleType: "Mini Truck (1T)",
    capacityKg: 1000,
    baseFare: 800,
    ratePerKm: 18,
    availability: "Available Now",
    partnerName: "Kisan Gati Logistics",
    rating: 4.8,
  },
  {
    id: "tr-02",
    vehicleType: "Eicher (3T)",
    capacityKg: 3000,
    baseFare: 1600,
    ratePerKm: 28,
    availability: "In 2 Hours",
    partnerName: "AgroExpress Haulers",
    rating: 4.9,
  },
  {
    id: "tr-03",
    vehicleType: "Reefer Cold Van (4T)",
    capacityKg: 4000,
    baseFare: 2800,
    ratePerKm: 42,
    availability: "Available Now",
    partnerName: "ColdChain Direct Fleet",
    rating: 4.7,
  },
  {
    id: "tr-04",
    vehicleType: "Heavy Truck (10T)",
    capacityKg: 10000,
    baseFare: 4500,
    ratePerKm: 65,
    availability: "Scheduled",
    partnerName: "Maharashtra State Transporters",
    rating: 4.6,
  },
];

export const initialFarmerVehicles: FarmerVehicle[] = [
  {
    id: "fv-01",
    ownerFarmerName: "Rameshwar Patil (आपले वाहन)",
    ownerPhone: "9822481920",
    village: "Dindori",
    taluka: "Dindori, Nashik",
    vehicleModel: "Mahindra Bolero Pik-Up (1.7T Heavy)",
    vehicleNumber: "MH-15-EG-4421",
    vehicleCategory: "Pickup / Light Truck",
    capacityKg: 1700,
    ratePerKm: 22,
    baseFare: 900,
    features: ["Tarpaulin Weather Cover", "Plastic Crate Racks", "GPS Tracking Enabled"],
    availability: "Available Now",
    rating: 4.9,
    completedTrips: 34,
    createdAt: "2026-08-10",
  },
  {
    id: "fv-02",
    ownerFarmerName: "Santosh Deshmukh",
    ownerPhone: "9822019482",
    village: "Pimpalgaon Baswant",
    taluka: "Niphad, Nashik",
    vehicleModel: "Tata 407 LPT (3.5T Cargo)",
    vehicleNumber: "MH-15-DS-8819",
    vehicleCategory: "Medium Eicher / 407",
    capacityKg: 3500,
    ratePerKm: 29,
    baseFare: 1500,
    features: ["Heavy Cargo Grille", "Ventilated Vegetables Bed", "Dual Driver for Long Haul"],
    availability: "Available Now",
    rating: 4.8,
    completedTrips: 52,
    createdAt: "2026-07-22",
  },
  {
    id: "fv-03",
    ownerFarmerName: "Bhausaheb Shinde",
    ownerPhone: "9422789123",
    village: "Ozar Mig",
    taluka: "Nashik Rural",
    vehicleModel: "John Deere 5050D with High-Side Trolley",
    vehicleNumber: "MH-15-TR-1290",
    vehicleCategory: "Tractor-Trolley",
    capacityKg: 4000,
    ratePerKm: 20,
    baseFare: 700,
    features: ["Hydraulic Tipping", "Ideal for Local Mandi Haulage (within 35km)", "Rough Road Capable"],
    availability: "Available Tomorrow",
    rating: 4.7,
    completedTrips: 28,
    createdAt: "2026-08-30",
  },
  {
    id: "fv-04",
    ownerFarmerName: "Ganesh Gaikwad",
    ownerPhone: "9823145678",
    village: "Sinnar",
    taluka: "Sinnar, Nashik",
    vehicleModel: "Eicher Pro 2049 (4.2T 14-Foot Container)",
    vehicleNumber: "MH-15-FC-6632",
    vehicleCategory: "Medium Eicher / 407",
    capacityKg: 4200,
    ratePerKm: 32,
    baseFare: 1800,
    features: ["Insulated Body", "Direct Fastag for Samruddhi & Expressway", "Fast Route Permit"],
    availability: "On Trip / Busy",
    rating: 4.9,
    completedTrips: 61,
    createdAt: "2026-06-15",
  },
];

export const initialTransportBookingRequests: TransportBookingRequest[] = [
  {
    id: "tbr-101",
    vehicleId: "fv-01",
    vehicleModel: "Mahindra Bolero Pik-Up (MH-15-EG-4421)",
    requesterFarmerName: "Pandurang Kadam",
    requesterPhone: "9822456712",
    requesterVillage: "Wani Khurd, Dindori",
    cropName: "Tomato (Abhinav Red)",
    loadWeightKg: 1400,
    pickupLocation: "Kadam Farm, Gate 4, Wani",
    destinationMandi: "Mumbai Vashi APMC",
    distanceKm: 170,
    proposedDate: "Tomorrow 05:00 AM",
    estimatedFare: 4640,
    status: "Pending Approval",
    createdAt: "Today, 10:30 AM",
    notes: "Cratered tomatoes ready for morning auction. Tarpaulin cover needed.",
  },
  {
    id: "tbr-102",
    vehicleId: "fv-01",
    vehicleModel: "Mahindra Bolero Pik-Up (MH-15-EG-4421)",
    requesterFarmerName: "Vasantrao Jadhav",
    requesterPhone: "9765432109",
    requesterVillage: "Chitegaon, Niphad",
    cropName: "Red Onion (Nashik Special)",
    loadWeightKg: 1600,
    pickupLocation: "Jadhav Vasti, Chitegaon",
    destinationMandi: "Pune Gultekdi Mandi",
    distanceKm: 180,
    proposedDate: "Day after tomorrow 06:00 AM",
    estimatedFare: 4860,
    status: "Accepted",
    createdAt: "Yesterday, 04:15 PM",
    notes: "Packed in 50kg jute sacks. Advance token payment confirmed.",
  },
];

export const initialSplitPools: SplitTransportPool[] = [
  {
    id: "pool-01",
    hostFarmerName: "Rameshwar Patil",
    hostPhone: "9822481920",
    originTaluka: "Dindori & Niphad Belt",
    destinationMandi: "Mumbai Vashi APMC",
    distanceKm: 170,
    departureTime: "Tomorrow 04:30 AM",
    departureDate: "Sep 21, 2026",
    vehicleType: "Eicher 14-Foot (4,000 kg Capacity)",
    totalCapacityKg: 4000,
    totalTripFare: 5200,
    status: "Open for Sharing",
    notes: "Kasara Ghat express transit via Samruddhi feeder. Looking for 1 or 2 farmers to share remaining 1,600 kg capacity to split diesel & freight.",
    participants: [
      {
        id: "part-1",
        farmerName: "Rameshwar Patil (Host)",
        phone: "9822481920",
        village: "Dindori",
        crop: "Tomato (Abhinav)",
        loadWeightKg: 2400,
        splitCost: 3120,
        joinedAt: "Created by Host",
      },
    ],
  },
  {
    id: "pool-02",
    hostFarmerName: "Kishor Sonawane",
    hostPhone: "9823901245",
    originTaluka: "Pimpalgaon & Ozar Belt",
    destinationMandi: "Pune Gultekdi Mandi",
    distanceKm: 180,
    departureTime: "Tomorrow 05:30 AM",
    departureDate: "Sep 21, 2026",
    vehicleType: "Tata 407 (3,500 kg Capacity)",
    totalCapacityKg: 3500,
    totalTripFare: 4700,
    status: "Open for Sharing",
    notes: "Direct trip to Pune Gultekdi gate 2. 1,500 kg space available for onion/pomegranate lots.",
    participants: [
      {
        id: "part-2",
        farmerName: "Kishor Sonawane (Host)",
        phone: "9823901245",
        village: "Pimpalgaon",
        crop: "Pomegranate (Bhagwa)",
        loadWeightKg: 2000,
        splitCost: 2685,
        joinedAt: "Created by Host",
      },
      {
        id: "part-3",
        farmerName: "Mahesh Gite",
        phone: "9822198001",
        village: "Ozar",
        crop: "Capsicum (Green)",
        loadWeightKg: 700,
        splitCost: 940,
        joinedAt: "Joined 2 hrs ago",
      },
    ],
  },
  {
    id: "pool-03",
    hostFarmerName: "Anand Jagtap",
    hostPhone: "9423451122",
    originTaluka: "Sinnar Industrial Belt",
    destinationMandi: "Surat APMC (Gujarat)",
    distanceKm: 230,
    departureTime: "Sep 22, 03:00 AM",
    departureDate: "Sep 22, 2026",
    vehicleType: "Reefer Cold Van (4,000 kg)",
    totalCapacityKg: 4000,
    totalTripFare: 6800,
    status: "Open for Sharing",
    notes: "Refrigerated transit for export tomatoes and grapes. Splitting saves ₹3,000+ per farmer.",
    participants: [
      {
        id: "part-4",
        farmerName: "Anand Jagtap (Host)",
        phone: "9423451122",
        village: "Sinnar",
        crop: "Grapes (Thompson)",
        loadWeightKg: 2200,
        splitCost: 3740,
        joinedAt: "Created by Host",
      },
    ],
  },
];

export const initialVerifiedBuyers: VerifiedBuyerMatch[] = [
  {
    id: "vb-01",
    name: "Metro Fresh Hypermarkets",
    type: "Supermarket Chain",
    location: "Pune & Mumbai (12 outlets)",
    distanceKm: 165,
    cropsNeeded: ["Tomato", "Onion", "Capsicum"],
    quantityNeededKg: 8000,
    desiredGrade: "Grade A",
    maxBudgetPerKg: 35,
    paymentReliabilityScore: 99,
    matchScore: 96,
    verified: true,
    buyerTrustMetrics: {
      confidenceScore: 99,
      avgPaymentDays: 0.5,
      paymentSpeedLabel: "Instant (Within 12h of weighment)",
      farmerReviewRating: 4.9,
      totalFarmerReviews: 48,
      completedTradesCount: 142,
      totalPayoutAmount: 4820000,
      disputeRatePercent: 0.2,
      kycVerified: true,
      gstApmcLicenseVerified: true,
      zeroDefaultGuarantee: true,
      recentReviews: [
        {
          farmerName: "Devidas Wagh",
          village: "Khed, Pune",
          rating: 5,
          daysToPay: 0.5,
          comment: "Full payment auto-released the exact afternoon truck was unloaded. Very clean dealing.",
          date: "Yesterday",
        },
        {
          farmerName: "Gopal Patil",
          village: "Niphad",
          rating: 4.9,
          daysToPay: 1,
          comment: "Exact weighbridge slip provided, zero unneeded deductions on tomato crates.",
          date: "4 days ago",
        },
      ],
    },
  },
  {
    id: "vb-02",
    name: "Kisan Rath Wholesale Consortium",
    type: "Wholesale Mandi Trader",
    location: "Vashi Navi Mumbai",
    distanceKm: 175,
    cropsNeeded: ["Tomato", "Potato", "Onion"],
    quantityNeededKg: 15000,
    desiredGrade: "Grade A",
    maxBudgetPerKg: 34,
    paymentReliabilityScore: 97,
    matchScore: 94,
    verified: true,
    buyerTrustMetrics: {
      confidenceScore: 96,
      avgPaymentDays: 1.0,
      paymentSpeedLabel: "Fast (Within 24 hours of delivery)",
      farmerReviewRating: 4.8,
      totalFarmerReviews: 62,
      completedTradesCount: 215,
      totalPayoutAmount: 8900000,
      disputeRatePercent: 0.4,
      kycVerified: true,
      gstApmcLicenseVerified: true,
      zeroDefaultGuarantee: true,
      recentReviews: [
        {
          farmerName: "Shankar Thorat",
          village: "Dindori",
          rating: 4.8,
          daysToPay: 1,
          comment: "High volume bulk buyer, always deposits 100% in escrow before lifting produce.",
          date: "3 days ago",
        },
      ],
    },
  },
  {
    id: "vb-03",
    name: "FarmToFork Organic D2C",
    type: "Retail Chain",
    location: "Thane West",
    distanceKm: 150,
    cropsNeeded: ["Tomato", "Grapes", "Green Chilies"],
    quantityNeededKg: 2000,
    desiredGrade: "Grade A",
    maxBudgetPerKg: 38,
    paymentReliabilityScore: 98,
    matchScore: 92,
    verified: true,
    buyerTrustMetrics: {
      confidenceScore: 97,
      avgPaymentDays: 0.8,
      paymentSpeedLabel: "Prompt (Same-Day / Next-Morning)",
      farmerReviewRating: 4.9,
      totalFarmerReviews: 34,
      completedTradesCount: 95,
      totalPayoutAmount: 3100000,
      disputeRatePercent: 0.1,
      kycVerified: true,
      gstApmcLicenseVerified: true,
      zeroDefaultGuarantee: true,
      recentReviews: [
        {
          farmerName: "Tukaram Shinde",
          village: "Niphad",
          rating: 5,
          daysToPay: 1,
          comment: "Premium pay for organic Thompson grapes, very transparent quality sorting.",
          date: "1 week ago",
        },
      ],
    },
  },
  {
    id: "vb-04",
    name: "Pawar Food Processing Ltd",
    type: "Processing Unit",
    location: "Sinnar, Nashik",
    distanceKm: 28,
    cropsNeeded: ["Tomato", "Onion"],
    quantityNeededKg: 25000,
    desiredGrade: "Grade B",
    maxBudgetPerKg: 29,
    paymentReliabilityScore: 95,
    matchScore: 89,
    verified: true,
    buyerTrustMetrics: {
      confidenceScore: 94,
      avgPaymentDays: 1.5,
      paymentSpeedLabel: "Standard (1-2 Days Escrow)",
      farmerReviewRating: 4.7,
      totalFarmerReviews: 41,
      completedTradesCount: 110,
      totalPayoutAmount: 5600000,
      disputeRatePercent: 0.6,
      kycVerified: true,
      gstApmcLicenseVerified: true,
      zeroDefaultGuarantee: true,
      recentReviews: [
        {
          farmerName: "Balasaheb Kadam",
          village: "Kopargaon",
          rating: 4.7,
          daysToPay: 2,
          comment: "Reliable industrial factory buyer for sauce tomatoes. Direct factory weighbridge.",
          date: "2 weeks ago",
        },
      ],
    },
  },
];

export const initialOrders: TransactionOrder[] = [
  {
    id: "ORD-9842",
    lotId: "lot-1020",
    crop: "Tomato (Hybrid Grade A)",
    quantityKg: 1800,
    pricePerKg: 33,
    totalAmount: 59400,
    sellerName: "Ramesh Patil",
    sellerLocation: "Dindori, Nashik",
    buyerName: "Metro Fresh Hypermarkets",
    buyerLocation: "Kothrud, Pune",
    orderType: "Bulk Order",
    paymentStatus: "In Escrow",
    orderStatus: "In Transit",
    escrowStatus: "Dispatched",
    orderDate: "Yesterday, 3:15 PM",
    createdAt: "Yesterday, 3:15 PM",
    estimatedDelivery: "Today by 6:00 PM",
    transportVehicle: "Eicher 3T (MH-15-EG-4281)",
    trackingStep: 3,
    paymentMode: "UPI / Net Banking (Escrow Protected)",
    qualityGrade: "Grade A",
    calamityRefund: {
      hasCalamity: true,
      calamityType: "Unseasonal Hailstorm",
      claimStatus: "Disbursed / Credited",
      refundAmount: 26730,
      insuranceScheme: "PMFBY (Pradhan Mantri Fasal Bima) & Maharashtra SDRF",
      applicationId: "PMFBY-MH-2026-88192",
      dbtUtrNumber: "DBT-MH-AGRI-2026-98124",
      surveyDate: "Sep 10, 2026",
      disbursedDate: "Sep 12, 2026",
      lossPercentage: 45,
      govtAgency: "Dept of Agriculture & Farmers Welfare, Maharashtra",
      remarks: "45% standing crop damage due to unseasonal hailstones in Dindori taluka. Compensation 100% credited via direct benefit transfer.",
    },
  },
  {
    id: "ORD-9811",
    crop: "Onion (Nashik Red Grade A)",
    quantityKg: 3000,
    pricePerKg: 25.5,
    totalAmount: 76500,
    sellerName: "Ramesh Patil",
    sellerLocation: "Dindori, Nashik",
    buyerName: "Vashi Wholesalers Syndicate",
    buyerLocation: "APMC Sector 19, Vashi",
    orderType: "Bulk Order",
    paymentStatus: "Paid",
    orderStatus: "Delivered",
    escrowStatus: "Payment Released",
    orderDate: "Sep 08, 2026",
    createdAt: "Sep 08, 2026",
    paymentReleasedDate: "Sep 09, 2026",
    estimatedDelivery: "Sep 09, 2026",
    transportVehicle: "Mini Truck 1T",
    trackingStep: 4,
    paymentMode: "Direct Bank Payout",
    ratingGiven: 5,
    reviewComment: "Crisp and well cured onions. Exact weight verified at mandi scale. Prompt delivery.",
    qualityGrade: "Grade A",
    calamityRefund: {
      hasCalamity: true,
      calamityType: "Excess Rain & Waterlogging",
      claimStatus: "Approved (Pending DBT)",
      refundAmount: 18500,
      insuranceScheme: "Maharashtra Natural Calamity SDRF Relief Fund",
      applicationId: "SDRF-NSK-2026-4421",
      surveyDate: "Sep 09, 2026",
      lossPercentage: 25,
      govtAgency: "Revenue & Disaster Management Dept, Govt of Maharashtra",
      remarks: "Field waterlogging panchnama verified by Taluka Krishi Adhikari. Sanction order released, payout in 24 hours.",
    },
  },
  {
    id: "ORD-9750",
    crop: "Fresh Farm Tomatoes (Household Pack)",
    quantityKg: 25,
    pricePerKg: 34,
    totalAmount: 850,
    sellerName: "Ramesh Patil",
    sellerLocation: "Dindori, Nashik",
    buyerName: "Anita Sharma",
    buyerLocation: "Baner, Pune",
    orderType: "Small Quantity",
    paymentStatus: "Paid",
    orderStatus: "Delivered",
    escrowStatus: "Payment Released",
    orderDate: "Sep 06, 2026",
    createdAt: "Sep 06, 2026",
    paymentReleasedDate: "Sep 07, 2026",
    estimatedDelivery: "Sep 07, 2026",
    trackingStep: 4,
    paymentMode: "UPI / Net Banking (Escrow Protected)",
    ratingGiven: 5,
    reviewComment: "Super fresh! Much better than supermarket store quality and at half the price.",
    qualityGrade: "Grade A",
    calamityRefund: {
      hasCalamity: false,
      claimStatus: "None / Normal Harvest",
      remarks: "Standard harvest without calamity impact. Normal direct market trade settled via escrow.",
    },
  },
  {
    id: "ORD-9690",
    crop: "Table Potatoes (Grade B)",
    quantityKg: 50,
    pricePerKg: 22,
    totalAmount: 1100,
    sellerName: "Sunita Deshmukh",
    sellerLocation: "Baramati, Pune",
    buyerName: "Anita Sharma",
    buyerLocation: "Baner, Pune",
    orderType: "Small Quantity",
    paymentStatus: "In Escrow",
    orderStatus: "In Transit",
    escrowStatus: "Payment in Escrow",
    orderDate: "Sep 12, 2026",
    createdAt: "Sep 12, 2026",
    estimatedDelivery: "Tomorrow by 11:00 AM",
    trackingStep: 2,
    paymentMode: "UPI / Net Banking (Escrow Protected)",
    qualityGrade: "Grade B",
    calamityRefund: {
      hasCalamity: true,
      calamityType: "Pest Outbreak / Frost",
      claimStatus: "Survey in Progress",
      insuranceScheme: "PMFBY Weather-Based Crop Insurance Scheme (WBCIS)",
      applicationId: "PMFBY-PUN-2026-1934",
      surveyDate: "Sep 14, 2026",
      lossPercentage: 30,
      govtAgency: "Agriculture Insurance Company of India (AIC)",
      remarks: "Field assessment scheduled with Gram Sevak & insurance surveyor. Drone photography completed.",
    },
  },
];

export const initialCalamityClaims: GovtCalamityClaimRecord[] = [
  {
    id: "CLM-MH-9481",
    vkNumber: "VK-MH-2026-94810",
    orderId: "ORD-9842",
    lotId: "lot-1020",
    crop: "Tomato (Hybrid Grade A)",
    cropVariety: "Abhinav F1 Hybrid",
    cropStage: "Fruiting & Harvest Stage",
    district: "Nashik",
    taluka: "Dindori",
    village: "Janori",
    gatNumber: "Gat No. 42/B, Survey No. 118",
    damagedArea: "2.5 Acres (१ हेक्टर)",
    calamityType: "Unseasonal Hailstorm & Cloudburst",
    calamityDetails: "Severe hailstones (30mm) accompanied by sudden cloudburst waterlogging damaged tomato crops at peak picking stage.",
    dateOfDamage: "Sep 07, 2026",
    eventDate: "Sep 07, 2026",
    surveyorOfficer: "V. R. Jagtap (Taluka Agriculture Officer)",
    lossPercentage: 45,
    assessedDamageValue: 59400,
    approvedRefundAmount: 26730,
    status: "Approved",
    aadhaarNumber: "XXXX-XXXX-9402",
    aadhaarMobile: "+91 98221 48190",
    aadhaarSeedingStatus: "Aadhaar Seeded & Active",
    hasSevenTwelveExtract: true,
    sevenTwelveDocName: "7-12_Extract_Gat42B_Janori.pdf",
    hasEightAExtract: true,
    eightAExtractDocName: "8-A_KhataExtract_No118.pdf",
    hasBankPassbook: true,
    bankPassbookDocName: "Bank_Passbook_Front_Copy.jpg",
    fieldMediaFiles: [
      { type: "photo", name: "Field_Damage_Hail_WideView.jpg", size: "2.8 MB" },
      { type: "video", name: "Field_Waterlogging_Walkthrough.mp4", size: "12.4 MB" },
    ],
    schemeName: "Pradhan Mantri Fasal Bima Yojana (PMFBY) + State SDRF Relief",
    sanctionDate: "Sep 12, 2026",
    supportHelpline: "14447 (PMFBY Toll Free)",
    surveyReportNumber: "PANCHNAMA-DIN-2026-7882",
    assignedAgencies: {
      localAgriOffice: "Taluka Krishi Adhikari Karyalaya, Dindori",
      revenueOfficer: "Circle Revenue Officer / Talathi, Janori",
      insuranceCompany: "Agriculture Insurance Company of India (AIC)",
    },
    suggestedSteps: [
      "Spot e-Panchnama completed & official VK Number auto-generated",
      "Retain digital copy of e-Panchnama report and VK number for administrative records",
      "Agriculture and Revenue joint report has cleared this record",
    ],
    submittedDocuments: [
      { documentName: "7/12 Land Record (७/१२ उतारा)", type: "Land Title", status: "Verified" },
      { documentName: "8-A Khata Extract (८-अ खाते उतारा)", type: "Acreage Record", status: "Verified" },
      { documentName: "Aadhaar Card Copy (आधार कार्ड)", type: "ID Proof", status: "Verified" },
      { documentName: "Bank Passbook Copy (बँक पासबुक)", type: "Bank Mandate", status: "Verified" },
      { documentName: "PMFBY Sowing Intimation Receipt", type: "Policy", status: "Verified" },
      { documentName: "Field Photographs & Video Evidence", type: "Inspection", status: "Verified" },
    ],
  },
  {
    id: "CLM-MH-9320",
    vkNumber: "VK-MH-2026-93201",
    orderId: "ORD-9811",
    crop: "Onion (Nashik Red Grade A)",
    cropVariety: "Gavran Nashik Red",
    cropStage: "Bulb Development Stage",
    district: "Nashik",
    taluka: "Niphad",
    village: "Pimpalgaon Baswant",
    gatNumber: "Gat No. 104, Survey No. 45/2",
    damagedArea: "1.8 Acres (०.७२ हेक्टर)",
    calamityType: "Excess Rain & Extended Waterlogging",
    calamityDetails: "Continuous 72-hour torrential rainfall resulted in 2 feet standing water across onion raised beds, causing root rot.",
    dateOfDamage: "Aug 29, 2026",
    eventDate: "Aug 29, 2026",
    surveyorOfficer: "S. K. More (Gram Krishi Sahayak)",
    lossPercentage: 25,
    assessedDamageValue: 74000,
    approvedRefundAmount: 18500,
    status: "Approved",
    aadhaarNumber: "XXXX-XXXX-9402",
    aadhaarMobile: "+91 98221 48190",
    aadhaarSeedingStatus: "Aadhaar Seeded & Active",
    hasSevenTwelveExtract: true,
    sevenTwelveDocName: "7-12_Extract_Gat104_Niphad.pdf",
    hasEightAExtract: false,
    hasBankPassbook: true,
    bankPassbookDocName: "Passbook_Verified_Copy.pdf",
    fieldMediaFiles: [
      { type: "photo", name: "Onion_Plot_Waterlogged_Field.jpg", size: "3.1 MB" },
    ],
    schemeName: "Maharashtra State Disaster Response Fund (SDRF) Grant",
    sanctionDate: "Sep 13, 2026",
    supportHelpline: "1800-180-1551 (Kisan Helpline)",
    surveyReportNumber: "PANCHNAMA-NIPH-2026-5120",
    assignedAgencies: {
      localAgriOffice: "Taluka Krishi Adhikari Karyalaya, Niphad",
      revenueOfficer: "Circle Officer, Pimpalgaon",
      insuranceCompany: "HDFC ERGO General Insurance (PMFBY Cell)",
    },
    submittedDocuments: [
      { documentName: "7/12 Land Record (७/१२ उतारा)", type: "Land Title", status: "Verified" },
      { documentName: "Aadhaar Card Copy (आधार कार्ड)", type: "ID Proof", status: "Verified" },
      { documentName: "Bank Passbook Copy (बँक पासबुक)", type: "Bank Mandate", status: "Verified" },
      { documentName: "Field Geotagged Damage Photos", type: "Inspection", status: "Verified" },
    ],
  },
  {
    id: "CLM-MH-8845",
    crop: "Soybean (Yellow JS-335)",
    cropVariety: "JS-335 Certified",
    cropStage: "Pod Filling Stage",
    district: "Nashik",
    taluka: "Yeola",
    village: "Mukhed",
    gatNumber: "Gat No. 56, Survey No. 12",
    damagedArea: "2.0 Acres",
    calamityType: "Flash Flood & Soil Erosion",
    calamityDetails: "Local nala overflowed causing sudden gush of muddy water washing away soybean plants and topsoil.",
    dateOfDamage: "Sep 02, 2026",
    eventDate: "Sep 02, 2026",
    surveyorOfficer: "M. D. Rathod (Circle Inspector)",
    lossPercentage: 35,
    assessedDamageValue: 42000,
    approvedRefundAmount: 0,
    status: "Rejected",
    aadhaarNumber: "XXXX-XXXX-9402",
    aadhaarMobile: "+91 98221 48190",
    aadhaarSeedingStatus: "Aadhaar Seeded & Active",
    hasSevenTwelveExtract: true,
    sevenTwelveDocName: "7-12_Extract_Yeola_56.pdf",
    hasEightAExtract: true,
    eightAExtractDocName: "8-A_Disputed_Area_Extract.pdf",
    hasBankPassbook: true,
    bankPassbookDocName: "Bank_Passbook_Scanned.pdf",
    rejectionReason:
      "Acreage disparity: Physical inspection surveyed 1.2 Hectares whereas application claimed 2.0 Hectares. Supporting 8-A khata certificate required reconciliation.",
    schemeName: "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    supportHelpline: "14447 (PMFBY Grievance Toll-Free)",
    surveyReportNumber: "REV-SURV-2026-098",
    assignedAgencies: {
      localAgriOffice: "Taluka Krishi Adhikari Karyalaya, Yeola",
      revenueOfficer: "Talathi / Nayab Tehsildar Desk, Yeola",
      insuranceCompany: "Bajaj Allianz General Insurance",
    },
    submittedDocuments: [
      { documentName: "7/12 Land Record (७/१२ उतारा)", type: "Land Title", status: "Verified" },
      { documentName: "Aadhaar Card Copy (आधार कार्ड)", type: "ID Proof", status: "Verified" },
      { documentName: "Bank Passbook Copy (बँक पासबुक)", type: "Bank Mandate", status: "Verified" },
      { documentName: "8-A Khata Reconciliation Slip", type: "Certificate", status: "Pending" },
    ],
  },
  {
    id: "CLM-MH-9104",
    orderId: "ORD-9690",
    crop: "Table Potatoes (Jyoti)",
    cropVariety: "Kufri Jyoti",
    cropStage: "Vegetative / Tuber Initiation",
    district: "Pune",
    taluka: "Baramati",
    village: "Malegaon Khurd",
    gatNumber: "Gat No. 78/A, Survey No. 44",
    damagedArea: "1.5 Acres",
    calamityType: "Early Blight & Frost Damage",
    calamityDetails: "Sudden temperature drop to 5°C with heavy morning frost led to severe foliar leaf burn and premature blight.",
    dateOfDamage: "Sep 05, 2026",
    eventDate: "Sep 05, 2026",
    surveyorOfficer: "P. N. Patil (District Agrostologist)",
    lossPercentage: 30,
    assessedDamageValue: 33000,
    approvedRefundAmount: 9900,
    status: "Field Survey Underway",
    aadhaarNumber: "XXXX-XXXX-9402",
    aadhaarMobile: "+91 98221 48190",
    aadhaarSeedingStatus: "Aadhaar Seeded & Active",
    hasSevenTwelveExtract: true,
    sevenTwelveDocName: "7-12_Extract_Baramati_78A.pdf",
    hasEightAExtract: false,
    hasBankPassbook: true,
    bankPassbookDocName: "Bank_Passbook_Upload.jpg",
    fieldMediaFiles: [
      { type: "photo", name: "Frost_Blight_Crop_CloseUp.jpg", size: "2.4 MB" },
    ],
    schemeName: "Restructured Weather-Based Crop Insurance Scheme (RWBCIS)",
    supportHelpline: "14447 (PMFBY Helpline)",
    surveyReportNumber: "SURVEY-INSP-2026-092",
    assignedAgencies: {
      localAgriOffice: "Taluka Krishi Adhikari Karyalaya, Baramati",
      revenueOfficer: "Circle Revenue Inspector, Baramati",
      insuranceCompany: "Agriculture Insurance Company of India (AIC)",
    },
    suggestedSteps: [
      "Keep field in present damaged condition for drone & GPS cross-verification",
      "Have 7/12 record and bank passbook ready for spot inspection",
      "Attend the verification visit when the surveyor arrives tomorrow",
    ],
    submittedDocuments: [
      { documentName: "7/12 Land Record (७/१२ उतारा)", type: "Land Title", status: "Verified" },
      { documentName: "Aadhaar Card Link Copy", type: "ID Proof", status: "Verified" },
      { documentName: "Bank Passbook Copy", type: "Bank Mandate", status: "Verified" },
      { documentName: "Geotagged Damage Photo (Plot #42)", type: "Inspection", status: "Verified" },
    ],
  },
];

export const initialGrievances: GrievanceRecord[] = [
  {
    id: "GRV-301",
    orderId: "ORD-9650",
    crop: "Capsicum Green",
    farmerName: "Gopal Shinde",
    buyerName: "Anita Sharma",
    issueType: "Shortage in Weight",
    description: "Ordered 20 kg, received crate measured 18.2 kg gross at delivery checkpoint.",
    status: "Refund Processed",
    submittedAt: "Sep 04, 2026",
    refundAmount: 72,
  },
];

export const tomatoPriceForecast: PriceForecastPoint[] = [
  { day: "Sep 08", actualPrice: 27, predictedPrice: 27, lowerBound: 25, upperBound: 29, demandLevel: "Normal" },
  { day: "Sep 09", actualPrice: 28, predictedPrice: 28, lowerBound: 26, upperBound: 30, demandLevel: "Normal" },
  { day: "Sep 10", actualPrice: 29, predictedPrice: 29, lowerBound: 27, upperBound: 31, demandLevel: "Normal" },
  { day: "Sep 11", actualPrice: 30, predictedPrice: 30, lowerBound: 28, upperBound: 32, demandLevel: "High" },
  { day: "Sep 12", actualPrice: 31, predictedPrice: 31, lowerBound: 29, upperBound: 33, demandLevel: "High" },
  { day: "Today (Sep 13)", actualPrice: 33, predictedPrice: 33, lowerBound: 31, upperBound: 35, demandLevel: "High" },
  { day: "Sep 14 (Sun)", predictedPrice: 35, lowerBound: 33, upperBound: 37, demandLevel: "High" },
  { day: "Sep 15 (Mon)", predictedPrice: 38, lowerBound: 35, upperBound: 41, demandLevel: "Peak" },
  { day: "Sep 16 (Tue)", predictedPrice: 37, lowerBound: 34, upperBound: 40, demandLevel: "Peak" },
  { day: "Sep 17 (Wed)", predictedPrice: 34, lowerBound: 31, upperBound: 37, demandLevel: "Normal" },
  { day: "Sep 18 (Thu)", predictedPrice: 32, lowerBound: 29, upperBound: 35, demandLevel: "Normal" },
];

export const initialCattleKeepers: CattleKeeper[] = [
  {
    id: "CK-101",
    name: "Bhausaheb Jadhav",
    farmName: "Jadhav Dairy & Khillari Stud Farm",
    phone: "+91 98224 18590",
    altPhone: "+91 94231 67204",
    village: "Dindori",
    taluka: "Dindori",
    district: "Nashik",
    distanceKm: 4,
    verified: true,
    address: "Near Kisan Seva Kendra, Gat No. 142, Dindori-Vani Road",
    availableBreeds: [
      { type: "Cow", breed: "Gir (गीर गाय)", count: 4, purpose: "Milking / Dairy", healthTagged: true },
      { type: "Buffalo", breed: "Murrah (मुर्रा म्हैस)", count: 2, purpose: "Milking / Dairy", healthTagged: true },
      { type: "Bullock", breed: "Khillari (खिल्लार शेती बैलजोडी)", count: 2, purpose: "Ploughing / Farm Work", healthTagged: true },
    ],
  },
  {
    id: "CK-102",
    name: "Vitthalrao Gaikwad",
    farmName: "Gaikwad Pashupalan Kendra",
    phone: "+91 97632 54109",
    village: "Ozar",
    taluka: "Niphad",
    district: "Nashik",
    distanceKm: 9,
    verified: true,
    address: "Ozar-Sukene Link Road, Behind Taluka Mandi",
    availableBreeds: [
      { type: "Cow", breed: "Sahiwal (साहिवाल गाय)", count: 3, purpose: "Milking / Dairy", healthTagged: true },
      { type: "Buffalo", breed: "Jaffarabadi (जाफराबादी म्हैस)", count: 3, purpose: "Milking / Dairy", healthTagged: true },
      { type: "Bullock", breed: "Dangi (डांगी मशागत बैल)", count: 2, purpose: "Ploughing / Farm Work", healthTagged: true },
    ],
  },
  {
    id: "CK-103",
    name: "Kailas Shinde",
    farmName: "Shinde Dairy & Livestock Breeders",
    phone: "+91 98901 23456",
    altPhone: "+91 98230 77123",
    village: "Pimpalgaon Baswant",
    taluka: "Niphad",
    district: "Nashik",
    distanceKm: 14,
    verified: true,
    address: "NH-3 Service Road, Agro Industrial Sector",
    availableBreeds: [
      { type: "Buffalo", breed: "Pandharpuri (पंढरपुरी देशी म्हैस)", count: 5, purpose: "Milking / Dairy", healthTagged: true },
      { type: "Cow", breed: "Phule Triveni (फुले त्रिवेणी संकरित)", count: 2, purpose: "Milking / Dairy", healthTagged: true },
    ],
  },
  {
    id: "CK-104",
    name: "Pandurang Deshmukh",
    farmName: "Deshmukh Sheti & Pashupalan",
    phone: "+91 94222 89012",
    village: "Sinnar Rural",
    taluka: "Sinnar",
    district: "Nashik",
    distanceKm: 22,
    verified: true,
    address: "Sinnar-Ghoti Road, Near Panchayati Lake",
    availableBreeds: [
      { type: "Bullock", breed: "Khillari (खिल्लार धष्टपुष्ट बैलजोडी)", count: 4, purpose: "Ploughing / Farm Work", healthTagged: true },
      { type: "Cow", breed: "Gir (गीर गाय)", count: 3, purpose: "Milking / Dairy", healthTagged: true },
      { type: "Goat", breed: "Osmanabadi (उस्मानाबादी शेळी)", count: 8, purpose: "Dairy / Breeding", healthTagged: true },
    ],
  },
  {
    id: "CK-105",
    name: "Sambhaji More",
    farmName: "More Gau-Sanrakshan Kendra",
    phone: "+91 98603 41782",
    village: "Chandwad",
    taluka: "Chandwad",
    district: "Nashik",
    distanceKm: 28,
    verified: true,
    address: "Near Old Toll Plaza, Chandwad Shivar",
    availableBreeds: [
      { type: "Cow", breed: "Dangi (डांगी डोंगराळ गाय)", count: 4, purpose: "Milking / Dairy", healthTagged: true },
      { type: "Buffalo", breed: "Murrah (मुर्रा दुभती म्हैस)", count: 3, purpose: "Milking / Dairy", healthTagged: true },
    ],
  },
  {
    id: "CK-106",
    name: "Ramdas Patil",
    farmName: "Patil Stud & Livestock Farm",
    phone: "+91 99215 76320",
    altPhone: "+91 98229 33411",
    village: "Yeola Rural",
    taluka: "Yeola",
    district: "Nashik",
    distanceKm: 35,
    verified: true,
    address: "Yeola-Manmad State Highway, Plot 8",
    availableBreeds: [
      { type: "Cow", breed: "Sahiwal & Gir Cross (साहिवाल-गीर)", count: 5, purpose: "Milking / Dairy", healthTagged: true },
      { type: "Buffalo", breed: "Mehsana (मेहसाणा म्हैस)", count: 2, purpose: "Milking / Dairy", healthTagged: true },
      { type: "Goat", breed: "Sirohi & Boer (शिरोही / बोएर शेळी)", count: 6, purpose: "Dairy / Breeding", healthTagged: true },
    ],
  },
];

export const initialRegisteredAccounts: RegisteredAccount[] = [
  {
    id: "MH-FARM-9402",
    role: "farmer",
    fullName: "Ramesh Tukaram Patil",
    phone: "9822012345",
    email: "ramesh.patil@krishivistar.in",
    state: "Maharashtra",
    district: "Nashik",
    taluka: "Dindori",
    village: "Dindori Shivar",
    pincode: "422202",
    password: "••••••••••",
    createdAt: "2026-01-10",
    verified: true,
    farmerDetails: {
      onlyCrops: false,
      primaryCrops: ["Tomato (Hybrid)", "Onion (Red)", "Grapes"],
      landAcres: 4.5,
      hasTransportVehicles: true,
      transportDetails: {
        vehicleType: "Mini Truck (Tata Ace 1T)",
        capacityTonnes: 1.2,
        vehicleNumber: "MH-15-EG-8291",
        willingToTransportForOthers: true,
      },
      hasCattle: true,
      cattleTotalCount: 4,
      cattleList: [
        {
          id: "c-1",
          type: "Cow",
          breed: "Gir (गीर गाय)",
          count: 2,
          milkingStatus: "Milking",
          milkYieldLpd: 16,
          tagNumber: "IN-889021",
        },
        {
          id: "c-2",
          type: "Buffalo",
          breed: "Murrah (मुर्रा म्हैस)",
          count: 2,
          milkingStatus: "Milking",
          milkYieldLpd: 18,
          tagNumber: "IN-889022",
        },
      ],
    },
  },
  {
    id: "BUYER-PUNE-402",
    role: "buyer",
    fullName: "Anita Sharma",
    phone: "9890054321",
    email: "anita.sharma@freshmart.com",
    state: "Maharashtra",
    district: "Pune",
    taluka: "Haveli",
    village: "Kothrud, Pune",
    pincode: "411038",
    password: "••••••••••",
    createdAt: "2026-02-14",
    verified: true,
    buyerDetails: {
      buyerType: "Household Consumer (Fresh Daily Orders)",
      businessName: "Fresh Consumer Co-op",
      monthlyProcurementKg: 250,
      preferredCrops: ["Tomato", "Onion", "Potato"],
    },
  },
];

